### ISSUE TITLE
Generated MCP server missing dart:io import causing 145+ undefined identifier errors

### ISSUE THREAD

**Issue by cdavis-code** [cdavis-code/easy_api_workspace#3]
## ✅ FIXED in v1.1.2

This issue has been **resolved** in `easy_api_generator` v1.1.2.

### Verification

After upgrading to v1.1.2 and regenerating the code:

1. ✅ The generated `.mcp.dart` file now correctly includes `import 'dart:io' as io;`
2. ✅ No compilation errors - the MCP server runs successfully
3. ✅ No undefined identifier errors for `io.Platform` or `io.stderr`

### Before (v1.1.0)
```
error • lib/src/oscar_mcp_server.mcp.dart:150:19 • Undefined name 'io'
... (145+ errors)
Error: The getter 'io' isn't defined for the type 'MCPServerWithTools'.
```

### After (v1.1.2)
```
Analyzing oscar_mcp...
No issues found!
```

### Upgrade Steps

To fix this issue in your project:

1. Update `pubspec.yaml`:
   ```yaml
   dev_dependencies:
     easy_api_generator: ^1.1.2
   ```

2. Run:
   ```bash
   dart pub get
   dart run build_runner build
   ```

3. Verify the generated file now includes:
   ```dart
   import 'dart:io' as io;
   ```

Thank you for the quick fix! 🎉
